const demoEvents = [
  {id:'fsbk-magny-cours',title:'FSBK Magny-Cours',date:'2026',location:'Circuit de Nevers Magny-Cours',description:"Un week-end au rythme du Championnat de France Superbike : vitesse, précision et tension dans les paddocks comme au bord de la piste.",cover:'image/Content_22.png',photos:['image/Content_22.png','image/Content_2.png','image/Content_3.png','image/Content_4.png','image/Content_5.png','image/Content_6.png']},
  {id:'race-day-le-mans',title:'Race Day Le Mans',date:'2025',location:'Circuit Bugatti, Le Mans',description:"Une journée de course saisie au plus près des pilotes et des équipes, des derniers réglages jusqu'au drapeau à damier.",cover:'image/Content_20.png',photos:['image/Content_20.png','image/Content_7.png','image/Content_8.png','image/Content_9.png']},
  {id:'endurance',title:'Endurance',date:'2025',location:'France',description:"Quand la course se prolonge, chaque relais raconte une nouvelle histoire. Un reportage sur l'effort collectif, la concentration et la lumière changeante.",cover:'image/Content_14.png',photos:['image/Content_14.png','image/Content_10.png','image/Content_11.png','image/Content_12.png']},
  {id:'paddock-stories',title:'Paddock Stories',date:'2025',location:'Dans les coulisses',description:"Avant le bruit de la piste, il y a les gestes précis, les regards et l'attente. Une immersion humaine dans les coulisses de la compétition.",cover:'image/Content_16.png',photos:['image/Content_16.png','image/Content_13.png','image/Content_15.png']},
  {id:'full-throttle',title:'Full Throttle',date:'2024',location:'Championnat vitesse',description:"Une série consacrée aux trajectoires, aux couleurs et à l'engagement total des pilotes lorsque la course prend toute sa vitesse.",cover:'image/Content_18.png',photos:['image/Content_18.png','image/Content_17.png','image/Content_19.png']},
  {id:'trackside',title:'Trackside',date:'2024',location:'Circuits de France',description:"Le point de vue du bord de piste : des compositions graphiques et des fractions de seconde qui transforment la vitesse en image.",cover:'image/Content_21.png',photos:['image/Content_21.png','image/Content_1.png']}
];

const openDB=()=>new Promise((resolve,reject)=>{const request=indexedDB.open('go2creation-events',1);request.onupgradeneeded=()=>request.result.createObjectStore('events',{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});
const getCustomEvents=async()=>{const db=await openDB();return new Promise(resolve=>{const request=db.transaction('events').objectStore('events').getAll();request.onsuccess=()=>resolve(request.result||[]);request.onerror=()=>resolve([])})};
const saveEvent=async event=>{const db=await openDB();return new Promise((resolve,reject)=>{const request=db.transaction('events','readwrite').objectStore('events').put(event);request.onsuccess=resolve;request.onerror=()=>reject(request.error)})};
const blobURL=value=>value instanceof Blob?URL.createObjectURL(value):value;
const safe=value=>{const el=document.createElement('span');el.textContent=value;return el.innerHTML};

async function renderArchive(){const list=document.querySelector('#event-list');if(!list)return;const custom=await getCustomEvents();const all=[...custom,...demoEvents];document.querySelector('#event-count').textContent=`${String(all.length).padStart(2,'0')} REPORTAGES`;list.innerHTML=all.map((event,index)=>`<a class="event-tile reveal visible tile-${index%6}" href="event.html?id=${encodeURIComponent(event.id)}"><img src="${blobURL(event.cover)}" alt="${safe(event.title)}"><span class="tile-index">${String(index+1).padStart(2,'0')}</span><div><p>${safe(event.location)} · ${safe(event.date)}</p><h2>${safe(event.title)}</h2><b>Voir le reportage ↗</b></div></a>`).join('')}

async function renderDetail(){const root=document.querySelector('#event-detail');if(!root)return;const id=new URLSearchParams(location.search).get('id');const custom=await getCustomEvents();const event=[...custom,...demoEvents].find(item=>item.id===id);if(!event){root.innerHTML='<section class="detail-loading"><h1>Événement introuvable.</h1><a href="events.html">Retour aux événements</a></section>';return}const images=event.files?event.files.map(blobURL):event.photos;document.title=`${event.title} — Go2Création`;root.innerHTML=`<section class="event-detail-hero"><img src="${blobURL(event.cover)}" alt="${safe(event.title)}"><div class="hero-shade"></div><div><a href="events.html">← Tous les événements</a><p>${safe(event.location)} · ${safe(event.date)}</p><h1>${safe(event.title)}</h1></div></section><section class="event-story section-pad"><p class="eyebrow">Le reportage</p><p>${safe(event.description)}</p><span>${String(images.length).padStart(2,'0')} PHOTOGRAPHIES</span></section><section class="event-photo-grid">${images.map((src,i)=>`<button class="gallery-item"><img src="${src}" alt="${safe(event.title)}, photographie ${i+1}" loading="lazy"></button>`).join('')}</section>`;root.addEventListener('click',e=>{const item=e.target.closest('.gallery-item');if(!item)return;const box=document.querySelector('.lightbox');box.querySelector('img').src=item.querySelector('img').src;box.showModal()})}

const dialog=document.querySelector('.upload-dialog');document.querySelector('.upload-open')?.addEventListener('click',()=>dialog.showModal());document.querySelector('.dialog-close')?.addEventListener('click',()=>dialog.close());const picker=document.querySelector('input[name="photos"]');picker?.addEventListener('change',()=>{const images=[...picker.files].filter(file=>file.type.startsWith('image/'));document.querySelector('#folder-status').textContent=`${images.length} image${images.length>1?'s':''} sélectionnée${images.length>1?'s':''}`});document.querySelector('#event-form')?.addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;const submit=form.querySelector('.form-submit');const files=[...form.photos.files].filter(file=>file.type.startsWith('image/'));if(!files.length)return;submit.disabled=true;submit.textContent='Import en cours…';const event={id:`custom-${Date.now()}`,title:form.title.value,date:new Date(`${form.date.value}T00:00`).toLocaleDateString('fr-FR',{year:'numeric',month:'long'}),location:form.location.value,description:form.description.value,cover:files[0],files};try{await saveEvent(event);dialog.close();await renderArchive();form.reset()}catch(error){alert("L'import n'a pas pu être enregistré. Le dossier est peut-être trop volumineux pour le stockage du navigateur.")}finally{submit.disabled=false;submit.innerHTML='Créer l’événement <b>↗</b>'}});

renderArchive();renderDetail();
